export const TOOL_DESCRIPTIONS = {
  status: "Use when you need index status or staleness.",
  refresh: "Use when you need to rebuild index state.",
  files: "Use when you need file path matches.",
  symbols: "Use when you need symbol name matches.",
  search: "Use when you need indexed keyword matches.",
  find_file: "Use when you need `files` behavior (compat alias).",
  find_symbol: "Use when you need `symbols` behavior (compat alias).",
  search_for_pattern: "Use when you need `search` behavior (compat alias).",
  lookup: "Use when you need ranked natural-language code context.",
  discover: "Use when you need one broad first retrieval call.",
  web_search: "Use when you need external docs or web references.",
  fetch_url: "Use when you need markdown-first page content from a URL.",
  git_status: "Use when you need branch or dirty-tree context.",
  git_log: "Use when you need commit history context.",
  git_diff: "Use when you need diff content for changes.",
  git_show: "Use when you need commit details for one revision.",
  gh_lookup: "Use when you need GitHub issues, PRs, checks, or repo bootstrap.",
  diagnostics: "Use when you need cache or latency diagnostics.",
} as const;

export const CLI_COMMANDS = [
  "build",
  "refresh",
  "status",
  "init",
  "discover",
  "lookup",
  "web-search",
  "fetch-url",
  "diagnostics",
  "git-status",
  "git-log",
  "git-diff",
  "git-show",
  "gh-lookup",
] as const;
