export const TOOL_DESCRIPTIONS = {
  status: "Use when you need index status or staleness.",
  refresh: "Use when you need to rebuild index state.",
  files: "Use when you need file path matches.",
  symbols: "Use when you need symbol name matches.",
  search: "Use when you need indexed keyword matches.",
  find_file: "Use when you need `files` behavior (compat alias).",
  find_symbol: "Use when you need `symbols` behavior (compat alias).",
  search_for_pattern: "Use when you need `search` behavior (compat alias).",
  lookup: "Use when you need ranked natural-language code context.",
  discover: "Use when you need one broad first retrieval call.",
  web_search: "Use when you need external docs or web references.",
  fetch_url: "Use when you need markdown-first page content from a URL.",
  git_status: "Use when you need branch or dirty-tree context.",
  git_log: "Use when you need commit history context.",
  git_diff: "Use when you need diff content for changes.",
  git_show: "Use when you need commit details for one revision.",
  gh_lookup: "Use when you need GitHub issues, PRs, checks, or repo bootstrap.",
  diagnostics: "Use when you need cache or latency diagnostics.",
} as const;

export const CLI_COMMANDS = [
  "build",
  "refresh",
  "status",
  "init",
  "discover",
  "lookup",
  "files",
  "symbols",
  "search",
  "web-search",
  "fetch-url",
  "grammar",
  "diagnostics",
  "git-status",
  "git-log",
  "git-diff",
  "git-show",
  "gh-lookup",
] as const;

export type CliCommandName = (typeof CLI_COMMANDS)[number];

export const CLI_COMMAND_DESCRIPTIONS: Record<CliCommandName, string> = {
  build: "Full index rebuild",
  refresh: "Incremental index rebuild",
  status: "Index freshness and manifest status",
  init: "Initialize setup for CLI or MCP mode",
  discover: "Combined discovery: files, symbols, search",
  lookup: "Ranked intent-aware retrieval",
  files: "File path lookup by query",
  symbols: "Symbol lookup by name",
  search: "Indexed code/content search",
  "web-search": "External web search across providers",
  "fetch-url": "Fetch and normalize URL content",
  grammar: "Manage parser language selections",
  diagnostics: "Cache and latency diagnostics",
  "git-status": "Git branch and dirty-tree summary",
  "git-log": "Recent git commits",
  "git-diff": "Working or ranged git diff",
  "git-show": "Show details for one git revision",
  "gh-lookup": "GitHub context lookup via gh CLI",
};
